package xdesign;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class EditarPedidoForm extends javax.swing.JFrame {

    private Pedido pedido;
    private ListarPedidosForm listarPedidosForm;

    public EditarPedidoForm(Pedido pedido, ListarPedidosForm listarPedidosForm) {
        initComponents();
        this.pedido = pedido;
        this.listarPedidosForm = listarPedidosForm;

        setTitle("Editar Pedido");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        // Cargar los datos del pedido en los campos del formulario
        txtId.setText(String.valueOf(pedido.getId()));
        cmbTipoCamiseta.setSelectedItem(pedido.getTipoCamiseta());
        cmbTalla.setSelectedItem(pedido.getTalla());
        txtCantidad.setText(String.valueOf(pedido.getCantidad()));
        txtCodigoDiseno.setText(pedido.getCodigoDiseno());
        cmbTipoPedido.setSelectedItem(pedido.getTipoPedido());
        txtDireccionEntrega.setText(pedido.getDireccionEntrega());
        cmbFormaPago.setSelectedItem(pedido.getFormaPago());
        txtNumeroTelefonico.setText(pedido.getNumeroTelefonico());
        txtNombreCliente.setText(pedido.getNombreCliente());

        //metodo de la clase imageicon para importar la imagen mediante el directorio
        ImageIcon wallpaper = new ImageIcon("src/images/pedido.jpg");
        //objeto de la clase icon dentro del constructor llamamos a la variable wallpaper lseguido del metodo getimage getscaledistance 
        //(traemos el label y obtenemos el ancho  por el metodo getWidth(), alto por el metodo getHeight(), y por ultimo la escala mediante la clase Image el metodo .scaledefault())
        //con este metodo adaptamos el tamaño de la imagen al label que contiene la imagen
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel1.getWidth(),
                jLabel1.getHeight(), Image.SCALE_DEFAULT));

        //metodo setIcon para asignarle el wallpaper al label
        jLabel1.setIcon(icono);

        //metodo para que se apliquen los cambios realizados
        this.repaint();
    }

    private EditarPedidoForm() {
    }

    private void guardarCambios() {
        try {
            pedido.setTipoCamiseta(cmbTipoCamiseta.getSelectedItem().toString());
            pedido.setTalla(cmbTalla.getSelectedItem().toString());
            pedido.setCantidad(Integer.parseInt(txtCantidad.getText()));
            pedido.setCodigoDiseno(txtCodigoDiseno.getText());
            pedido.setTipoPedido(cmbTipoPedido.getSelectedItem().toString());
            pedido.setDireccionEntrega(txtDireccionEntrega.getText());
            pedido.setFormaPago(cmbFormaPago.getSelectedItem().toString());
            pedido.setNumeroTelefonico(txtNumeroTelefonico.getText());
            pedido.setNombreCliente(txtNombreCliente.getText());
            
                        // Validación de campos vacíos
            if (txtCodigoDiseno.getText().isEmpty() || txtNumeroTelefonico.getText().isEmpty() || txtNombreCliente.getText().isEmpty()
                    || txtDireccionEntrega.getText().isEmpty()) {
                throw new IllegalArgumentException("Todos los campos deben estar llenos.");
            }

            if (Integer.parseInt(txtCantidad.getText()) < 1 || Integer.parseInt(txtCantidad.getText()) > 99) {
                throw new IllegalArgumentException("La cantidad debe ser un número de 1 o 2 dígitos.");
            }

            if (!txtCodigoDiseno.getText().matches("[a-zA-Z0-9]+")) {
                throw new IllegalArgumentException("El código de diseño es inválido.");
            }

            if (txtNumeroTelefonico.getText().length() != 8 || !txtNumeroTelefonico.getText().matches("\\d+")) {
                throw new IllegalArgumentException("El número telefónico es inválido.");
            }

            JOptionPane.showMessageDialog(this, "Pedido actualizado exitosamente.");
            listarPedidosForm.actualizarTabla(); // Actualizar la tabla en ListarPedidosForm
            dispose(); // Cerrar la ventana de edición
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoDiseno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbTipoCamiseta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbTipoPedido = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbTalla = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbFormaPago = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroTelefonico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccionEntrega = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("ID Pedido");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtId.setEnabled(false);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 110, -1));

        jLabel4.setText("Codigo de diseño");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        getContentPane().add(txtCodigoDiseno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 110, -1));

        jLabel11.setText("Nombre cliente");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 240, -1));

        jLabel2.setText("Tipo camisa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        cmbTipoCamiseta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lisa manga larga ", "Polo manga corta ", "Estampado manga corta", "Lisa manga corta", "Deportiva manga larga", "Deportiva manga corta", "Deportiva sin mangas" }));
        getContentPane().add(cmbTipoCamiseta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, -1));

        jLabel5.setText("Tipo pedido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        cmbTipoPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Envío a domicilio", "Recoger en tienda" }));
        cmbTipoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, -1));

        jLabel3.setText("Talla");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        cmbTalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL", "2XL" }));
        cmbTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTallaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 110, -1));

        jLabel9.setText("Forma pago");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        cmbFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Sinpe móvil", "Transferencia bancaria", "Tarjeta de débito/crédito" }));
        getContentPane().add(cmbFormaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 110, -1));

        jLabel7.setText("Cantidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 110, -1));

        jLabel8.setText("Télefono cliente");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));
        getContentPane().add(txtNumeroTelefonico, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 110, -1));

        jLabel10.setText("Dirección de entrega");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));
        getContentPane().add(txtDireccionEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 230, -1));

        jButton1.setText("Guardar cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Editar pedido");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void cmbTipoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoPedidoActionPerformed
        if (cmbTipoPedido.getSelectedItem().equals("Envío a domicilio")) {
            txtDireccionEntrega.setEnabled(true);
        } else {
            txtDireccionEntrega.setEnabled(false);
        }
    }//GEN-LAST:event_cmbTipoPedidoActionPerformed

    private void cmbTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTallaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardarCambios();


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPedidoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPedidoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPedidoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPedidoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPedidoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbFormaPago;
    private javax.swing.JComboBox<String> cmbTalla;
    private javax.swing.JComboBox<String> cmbTipoCamiseta;
    private javax.swing.JComboBox<String> cmbTipoPedido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoDiseno;
    private javax.swing.JTextField txtDireccionEntrega;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumeroTelefonico;
    // End of variables declaration//GEN-END:variables
}
